site_name: Dashboard and Notifications
site_description: 'PIXEL Dashboard & Notifications Documentation Hub'
site_author: 'José Antonio Clemente'

# this allows visualizing content in github as anonympus user without having to log in
edit_uri: blob/master/docs/

theme: readthedocs

# we will use the same style as for the general PIXEL documentation hub (based on FIWARE and a readthedocs theme)
extra_css:
    - css/pixel_a.css
    - css/pixel_b.css
    - css/monokai_sublime_.css
    - css/pigments-monokai.css

repo_url: https://github.com/pixel-ports/ot-docs-dashboard

pages:
    - Home: index.md
    - Developer's Guide: 'devel_guide.md'
        

copyright: Apache License 2.0

extra:
  version: 1.0.0
  color: 26b3c3
